### ISSUE TITLE
Best way to edit a task?

### ISSUE THREAD

**Issue by skbolton** [ad-si/TaskLite#11]
Without having to edit SQLite directly Is there a way to edit a task? So far I have messed up the text of a task and wanted to retag a task

**Comment by ad-si** [comment]
I just released [TaskLite 0.3](https://github.com/ad-si/TaskLite/releases/tag/v0.3.0.0) which adds an edit command (commit https://github.com/ad-si/TaskLite/commit/1add89e) 🎉.

This should be exactly what you're looking for 😁. Let me now if it works for you!
