### ISSUE TITLE
More examples?

### ISSUE THREAD

**Issue by anojo** [ad-si/TaskLite#30]
Do you have some more examples to get me started?

Say I want, for example, to add a tag to all the tasks that result from some search -- or any bulk action of the sort. How would you go about it?

(If this is not the medium to be asking these things, just let me know, sorry.)

**Comment by anojo** [comment]
Unrelated, but not to pollute the issues, I'll ask here.

I created a task, set it to wait, but it is still listed under the `ready` command (though the priority is lower and now it is also listed under `waiting`). But those states should be exclusive, right?

**Comment by ad-si** [comment]
> Say I want, for example, to add a tag to all the tasks that result from some search -- or any bulk action of the sort. How would you go about it?

To bulk tag several tasks:

`tl tag myproject 4hf5 7fh3 f66d 4hf7`

Unfortunately there is no direct way to get the ULIDs from some search. I plan to support this in the future:

`tl tag myproject $(tl get --ulids +oldproject)`

**Comment by ad-si** [comment]
> I created a task, set it to wait, but it is still listed under the `ready` command (though the priority is lower and now it is also listed under `waiting`). But iiuc those states should be exclusive, right?

There are still a few issues with the states. I added the issue to my internal list. Thanks!
