### ISSUE TITLE
Is the Frozen status implemented?

### ISSUE THREAD

**Issue by Profpatsch** [ad-si/TaskLite#31]
The manual states that there is a tertiary state called `Frozen`, which stops recurrence and repetition:

> Frozen - Was previously repeating or recurring but has been stopped for the time being.

But looking through the commands and the source code the only mention of the word `frozen` is in this section of the manual, not anywhere in the source code.

**Comment by ad-si** [comment]
```
$ tl add buy milk
🆕 Added task "buy milk" with id "01em6a7rn7xcz8kqm5sda3jhdn"
 ~/Dropbox/Projects/TaskLite (master)  adrian@Adrians-MBP  105 p | -.29 p/d 

$ tl repeat PT50S 01em6a7rn7xcz8kqm5sda3jhdn
📅 Set repeat duration of task "buy milk" with id "01em6a7rn7xcz8kqm5sda3jhdn" to "PT50S"
 ~/Dropbox/Projects/TaskLite (master)  adrian@Adrians-MBP  105 p | -.29 p/d 

$ tl info 01em6a7rn7xcz8kqm5sda3jhdn

buy milk

   State: Open
Priority: 0.0
    ULID: 01em6a7rn7xcz8kqm5sda3jhdn

🆕  Created   2020-10-09 09:14:28
       ⬇
✏️   Modified  2020-10-09 09:14:36

Repetition Duration: PT50S
Group Ulid: 01em6a8096z4bw47km77b2nqvd
User: adrian


 ~/Dropbox/Projects/TaskLite (master)  adrian@Adrians-MBP  105 p | -.29 p/d 

$ tl unrepeat 01em6a7rn7xcz8kqm5sda3jhdn
💥 Removed repetition duration of task "buy milk" with id "01em6a7rn7xcz8kqm5sda3jhdn"
 ~/Dropbox/Projects/TaskLite (master)  adrian@Adrians-MBP  105 p | -.29 p/d 

$ tl info 01em6a7rn7xcz8kqm5sda3jhdn

buy milk

   State: Open
Priority: 0.0
    ULID: 01em6a7rn7xcz8kqm5sda3jhdn

🆕  Created   2020-10-09 09:14:28
       ⬇
✏️   Modified  2020-10-09 09:15:33

Group Ulid: 01em6a8096z4bw47km77b2nqvd
User: adrian
```

The task is now `Frozen`, since it is still part of a repetition group, but it has no more repetition or recurrence duration. So it's basically just a name for a valid scenario. Not sure if there are any further useful scenarios for this state.

**Comment by ngirard** [comment]
Hey @Profpatsch, can this issue be closed, or do you need any further clarification ?

**Comment by Profpatsch** [comment]
Sure, I didn’t really have time to investigate TaskLite any further so far.
