### ISSUE TITLE
createNextRep vs createNextRec use different iso duration parsing

### ISSUE THREAD

**Issue by Profpatsch** [ad-si/TaskLite#33]
https://github.com/ad-si/TaskLite/blob/a721fddaf977503e9f8b2d8fb8bf43a447cbd9e6/tasklite-core/source/Lib.hs#L503-L520

vs

https://github.com/ad-si/TaskLite/blob/a721fddaf977503e9f8b2d8fb8bf43a447cbd9e6/tasklite-core/source/Lib.hs#L444-L453

which uses 

https://github.com/ad-si/TaskLite/blob/a721fddaf977503e9f8b2d8fb8bf43a447cbd9e6/tasklite-core/source/Lib.hs#L429-L441

**Comment by ad-si** [comment]
Thanks a lot! Fixed in 95266bc
I guess that's the punishment for copy & pasting too much code 🙈
