### ISSUE TITLE
tasklite should create .config/tasklite

### ISSUE THREAD

**Issue by jdietrch** [ad-si/TaskLite#4]
I built tasklite from source, following the instructions here:
https://tasklite.org/installation/cli.html

It says to test the installation run `tasklite help`. I did so, and it failed:
```
jdietrch@saturn:~$ tasklite help
tasklite: /home/jdietrch/.config/tasklite: copyFile:atomicCopyFileContents:withReplacementFile:openBinaryTempFile: d
oes not exist (No such file or directory)
jdietrch@saturn:~$
```

Yes, a quick `mkdir .config/tasklite/` solved that problem, but perhaps tasklite could create that directory itself if it doesn't exist?

**Comment by KyleWJohnston** [comment]
Thanks! Adding the directory fixed my error as well. The `config.yaml` file was copied automatically.

I tried fixing the error by adding the following line to [tasklite-core/app/Main.hs](https://github.com/ad-si/TaskLite/blob/3e494f7ee1fa1c04c103167a376c32bdedd41edc/tasklite-core/app/Main.hs), but it resulted in a build error. I'm new to Haskell (and this project), so probably a basic mistake. Hopefully someone else can figure it out.
```
case configResult of
    Left error -> do
      if "not found" `T.isInfixOf` (T.pack $ prettyPrintParseException error)
      then do
+++     createDirectoryIfMissing True $ takeDirectory configPath
        exampleConfigPath <- getDataFileName "example-config.yaml"
        copyFile exampleConfigPath configPath
        configResult2 <- decodeFileEither configPath
```

**Comment by ad-si** [comment]
Thanks a lot for the heads up! Didn't expect `getXdgDirectory` to return a non existent directory 😒.
Turns out the documentation warned me: https://hackage.haskell.org/package/directory-1.3.5.0/docs/System-Directory.html#v:getXdgDirectory

> Note: The directory may not actually exist, in which case you would need to create it with file mode 700 (i.e. only accessible by the owner).

I fixed it now and tested it with a clean Ubuntu. Does it work for you as well @jdietrch ?

**Comment by jdietrch** [comment]
I'm not planning to test this myself, as I uninstalled tasklite a while ago; but it sounds like you've got it solved.

Thanks for working on this.

**Comment by ad-si** [comment]
> I'm not planning to test this myself, as I uninstalled tasklite a while ago

What would make you use it? 🤔I want to take TaskLite to the next level, which probably means listening to my users 😅.

**Comment by ad-si** [comment]
I talked to jdietrch about this in private, so the issue can be closed.
