### ISSUE TITLE
"tasklite prioritize VALUE TASK_ID" does not work for negative values

### ISSUE THREAD

**Issue by xsteve** [ad-si/TaskLite#54]
Example session:

% tl prioritize -3 1a64
Invalid option `-3'

Did you mean this?
    -h

Usage: tasklite prioritize VALUE TASK_ID ...
  Adjust priority of specified tasks

**Comment by ad-si** [comment]
Hi, that's a common problem (feature =P) of all CLI tools and the solution is equally common:
Use a `--` to indicate that all subsequent arguments are not flags

```sh
tl prioritize -- -3 1a64
```

**Comment by ad-si** [comment]
Since this is so common, I'm not sure if changing it would be an improvement or a surprising behavior …

**Comment by xsteve** [comment]
Thanks for your quick response. This work-around solves the problem for me.
However from a CLI perspective it is surprising that negative arguments are handled in a different way than positive arguments:
tl prioritize 3 1a64
tl prioritize -- -3 1a64
