### ISSUE TITLE
Command 'recur' broken/removed?

### ISSUE THREAD

**Issue by silentjay** [ad-si/TaskLite#55]
`tl recur P1M nrt` gives output of `invalid argument 'recur'`

Has this command been removed? It's no longer shown via the help command but is listed in the online docs?

**Comment by ad-si** [comment]
Uhm, that's strange. Did you accidentally install an old version of TaskLite?

**Comment by silentjay** [comment]
version 0.3.0.0+ed428cf2

**Comment by silentjay** [comment]
Ah nevermind I found a recent build in github actions page, cheers!
