### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by ixzh** [ad-si/TaskLite#57]
Hi, how can I resolve this?
```haskell
        ‘randomIO’ is not a (visible) method of class ‘R.Random’
       |
  98 |     randomIO = getULID
       |     ^^^^^^^^
```
Thanks!

**Comment by ad-si** [comment]
Oh, that's weird. Can you please write down the steps you executed to arrive at that error message? Normally `stack build` should be deterministic enough to work out of the box.

**Comment by ixzh** [comment]
I I changed the resolver to lts-18.12, and got this error...I'm using `stack install tasklite-core`

**Comment by ad-si** [comment]
Well, no wonder it doesn't work when you change the LTS version 🙈.
This issue needs to be resolved first: https://github.com/ad-si/ulid/issues/10

**Comment by ixzh** [comment]
cool! I will stick with the original then Thanks!
