### ISSUE TITLE
Suggestion: Add date shortcuts

### ISSUE THREAD

**Issue by silentjay** [ad-si/TaskLite#59]
Be handy to have a few date shortcuts for the due dates e.g. due:tmw and due:tdy

**Comment by ad-si** [comment]
This is probably not gonna happen, since the recommended way is to use [`tu`](https://github.com/ad-si/tu).
Check out the full explanation here: https://tasklite.org/concepts/main.html?highlight=tu#general
Therefore I'm closing it for the time being.
