### ISSUE TITLE
Weird effects from possible accidental upgrade?

### ISSUE THREAD

**Issue by silentjay** [ad-si/TaskLite#60]
I accidentally opened the tasklite executable with vim and even though I didn't make any changes/save anything I couldn't get it to run without errors after. No problem I thought, just download the latest release and replace, which I assumed I was running anyway.

I think I may have temporarily installed an old release, but am now using version 0.3.0.0+ed428cf2, when I complete tasks which have a 1 day repeat they automatically reappear as a new task which is due. Strange. So I try and reset the the repetition eg `tl repeat P1D fe5` but recieve errors `cannot parse value P1D. Usage: tasklite repeat NUM_OF_DAYS...`. I thought the newest version supported P1D, P1M etc? Was this type of input removed?

I really don't know what's going or how to solve it?

**Comment by ad-si** [comment]
Could you figure it out yourself?

This should work:

```txt
$ tl repeat P1D 01ft8sv7f4esh3dfwgk9x9823p
📅 Set repeat duration of task "buy milk" with id "01ft8sv7f4esh3dfwgk9x9823p" to "P1D"
```

**Comment by silentjay** [comment]
Yeah cheers I figured it out. I must have been originally running a build from github CI actions. When I reinstalled I used the latest release assuming it was the same but in fact is an older commit hence the strange results. 

Ended up building from source as the CI actions versions are expired, solved the issues.

**Comment by ad-si** [comment]
Great you figured it out! 🙌
And sorry for the hassle, I'm currently working on 0.4, but it takes me longer than anticipated. I should have released an intermediate 3.x 😅

**Comment by silentjay** [comment]
My fault for not remembering I was using a newer build. Looking forward to 0.4!
