### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by austinbutler** [ad-si/TaskLite#68]
I see 160 commits to master since the last release in 2020. Any plans for a new release?

**Comment by ad-si** [comment]
Yeah, I’m planing one, but I tried out a lot of things and it’s quite a mess right now. I’ll have to do a big clean up and finish or remove all the loose ends. So it’ll unfortunately take me a few more weeks 😅

**Comment by austinbutler** [comment]
Thanks, good luck!

**Comment by chenrui333** [comment]
any updates on this thread? :)

**Comment by ad-si** [comment]
Yes! I'm making steady progress. Already fixed 2 big issues:
Now all SQL queries are written the same way and the help output is fixed. I still have a list of several minor bugs I want to fix. So it'll take some more time, but we're getting there!

**Comment by ajimix** [comment]
I'm also looking for a new release, so far seems to be the best CLI task manager out there so seeing a new release would be amazing

**Comment by jpeeler** [comment]
You said [on HN](https://news.ycombinator.com/item?id=41375055) that a new release would come in a few weeks. Wanted to give a gentle nudge on keeping the recent momentum up!

(And do please close this issue once a new release is tagged.)

**Comment by ad-si** [comment]
We're getting there! Only 2 tasks left:

- [ ] Finish implementation of `pre-modify` and `post-modify` hook
- [ ] Edit mode: Fix modified time when state is set to `Done`

**Comment by ad-si** [comment]
IT IS DONE!
I just released the new version: https://github.com/ad-si/TaskLite/releases/tag/v0.4.0.0 🎉

Looking forward to hearing your feedback @austinbutler, @chenrui333, @ajimix, and @jpeeler! 😊
