### ISSUE TITLE
Would you support UDAs?

### ISSUE THREAD

**Issue by lyz-code** [ad-si/TaskLite#7]
Hi, I've been using taskwarrior for a long time, but I'm tired of their stagnation, so your project looks awesome.

I was wondering if you will support user defined attributes, for example to define the Kanban state of backlog, todo and doing.

I know you can achieve that same thing with tags, but I think it's a nice way to represent in the cli reports. Furthermore I've got like 7 different UDAs that I wouldn't like to loose

**Comment by ad-si** [comment]
> Hi, I've been using taskwarrior for a long time, but I'm tired of their stagnation, so your project looks awesome.

Thanks! 😊
I was also a devoted Taskwarrior user, but like you say, I was also tired of weird bugs which got never fixed 😔.

> I was wondering if you will support user defined attributes, for example to define the Kanban state of backlog, todo and doing.

Actually it's already supported, just the tooling is maybe a little lacking…

If you have a `test.json` file like
```json
{
    "body": "Buy milk",
    "kanban-state": "backlog"
}
```
and import it with
```sh
$ cat test.json | tl import
Importing … 📥 Imported task "Buy milk" with ulid "00000000000002wa0trck0m2ps"
```
all additional JSON fields are stored in the task's metadata field:

```sh
$ tl info 00000000000002wa0trck0m2ps
awake_utc: null
review_utc: null
state: null
repetition_duration: null
recurrence_duration: null
body: Buy milk
user: adrian
ulid: 00000000000002wa0trck0m2ps
modified_utc: 1970-01-01T00:00:00Z
group_ulid: null
closed_utc: null
priority_adjustment: null
metadata:
  body: Buy milk
  kanban-state: backlog
waiting_utc: null
ready_utc: null
due_utc: null
priority: 0.0
tags:

notes:
```

To access the the metadata key programmatically you can do something like:

```sh
tl ndjson | grep 00000000000002wa0trck0m2ps | jq '.metadata["kanban-state"]'
```

I should probably add a dedicated `tl metadata 00000000000002wa0trck0m2ps` command or similar to make this easier…

Does this good enough for your usecase, or do you need anything else?

**Comment by ad-si** [comment]
Or a probably cleaner solution:

```sh
tl runsql "select json_extract(metadata, '\$.kanban-state') from tasks where ulid == '00000000000003nvz9b8xkqkr4'" \
| tail -n 1
```

**Comment by lyz-code** [comment]
Yeah, it's enough. 

Thanks! :)

**Comment by ad-si** [comment]
Btw: I just added those infos in more detail to the documentation: https://tasklite.org/usage/cli.html#metadata
