### ISSUE TITLE
Webapp: Correctly set `state` when checking off a task

### ISSUE THREAD

**Issue by vbmithr** [ad-si/TaskLite#94]
When I use the left hand side checkbox in webapp, task gets deleted! Probably not a normal behaviour!

**Comment by ad-si** [comment]
It will not be shown anymore, as it was closed and `tasks_head` only shows open tasks.
(Or is it really deleted if you check with `tasklite all`?)

**Comment by vbmithr** [comment]
Still in DB. But not in closed either, i.e. not listed with `tl done`.

**Comment by ad-si** [comment]
Good catch! The `state` isn't set correctly!

**Comment by ad-si** [comment]
Fixed in 2f3febc
