### ISSUE TITLE
UNIQUE constraint failed: tasks.ulid

### ISSUE THREAD

**Issue by gour** [ad-si/TaskLite#96]
Hello,

not sure if it is due to my misunderstanding how the application does work, or is it some bug:

```
❯ tl all
Id   Prio  Opened UTC  Body        
cd1   9    2024-11-22  recurring test  2024-11-20  2024-11-22 10:01:40
375  15    2024-11-22  Mow the lawn  2020-10-01  2024-11-22 10:21:15
g6q   0    2024-11-22  Mow the lawn  2024-12-22 10:21:15


~ 
❯ tl open
Id   Prio  Opened UTC  Body        
g6q   0    2024-11-22  Mow the lawn  2024-12-22 10:21:15


~ 
❯ tl edit g6q
tasklite: SQLite3 returned ErrorConstraint while attempting to perform step: UNIQUE constraint failed: tasks.ulid
```

Any idea?

**Comment by ad-si** [comment]
Did you install it from source based on the latest commit?
The latest official release is known to have a few bugs like this. 😓

**Comment by gour** [comment]
> Did you install it from source based on the latest commit? The latest official release is known to have a few bugs like this. 😓

No, from the official release...

**Comment by gour** [comment]
> Did you install it from source based on the latest commit? The latest official release is known to have a few bugs like this. 

Just to confirm that after installing `ghcup` and buiding from the source. the above example does work. :smile:
